version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    environment: 
      - COMPOSE_CONVERT_WINDOWS_PATHS=1

    volumes:
      - ..:/go/src
      - /var/run/docker.sock:/var/run/docker.sock:rw
    
    command: sleep infinity
